apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: scenehunter-dev

namePrefix: dev-

commonLabels:
  environment: development

patchesStrategicMerge:
- deployment-patch.yaml
- ingress-patch.yaml

replicas:
- name: scenehunter-v2
  count: 1

images:
- name: app
  newTag: latest
